---
sidebar: sidebar 
permalink: concept_acquisition_unit_requirements.html 
summary: Der Server oder die VM, die Sie als Acquisition Unit verwenden, muss die Mindestanforderungen erfüllen. 
keywords: AU, acquisition unit, requirements, sizing 
---
= Anforderungen An Die Erfassungseinheit
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Sie müssen eine Acquisition Unit (AU) installieren, um Informationen aus Ihren Infrastrukturdatenkollektoren (Speicher, VM, Port, EC2 usw.) zu erhalten. Bevor Sie die Acquisition Unit installieren, sollten Sie sicherstellen, dass Ihre Umgebung den Anforderungen für Betriebssystem, CPU, Arbeitsspeicher und Festplattenspeicher entspricht.



== Anforderungen

|===


| Komponente | Linux-Anforderungen Erfüllt | Windows Anforderungen 


| Betriebssystem | Ein Computer, auf dem eine lizenzierte Version einer der folgenden Versionen ausgeführt wird:

* CentOS (64 Bit): 7.2 bis 7.9, 8.1 bis 8.4, Stream 8, Stream 9
* AlmaLinux 9.3 und 9.4
* Debian (64-bit): 9 und 10
* OpenSUSE Leap 15.1 bis 15.5
* Oracle Enterprise Linux (64 Bit): 7.5 bis 7.9, 8.1 bis 8.8
* Red hat Enterprise Linux (64 Bit): 7.2 bis 7.9, 8.1 bis 8.10, 9.1 bis 9.4
* Rocky 9.0 bis 9.4
* SUSE Enterprise Linux Server 15, 15 SP2 bis 15 SP5
* Ubuntu Server: 18.04, 20.04, 22.04 LTS
* SELinux auf den oben genannten Plattformen

Auf diesem Computer sollte keine andere Software auf Anwendungsebene ausgeführt werden. Es wird ein dedizierter Server empfohlen.

Wenn Sie mit SELinux arbeiten, wird empfohlen, die folgenden Befehle auf dem Erfassungseinheitssystem auszuführen:

 Sudo semanage fcontext -a -t usr_t "/opt/netapp/Cloudinsights(/.*)?“
 Sudo restorecon -R /opt/netapp/Cloud Insights | Ein Computer mit einer lizenzierten Version von einer der folgenden Komponenten: * Microsoft Windows 10 64-Bit * Microsoft Windows Server 2012 * Microsoft Windows Server 2012 R2 * Microsoft Windows Server 2016 * Microsoft Windows Server 2019 * Microsoft Windows Server 2022 * Microsoft Windows 11 auf diesem Computer sollte keine andere Software auf Anwendungsebene ausgeführt werden. Es wird ein dedizierter Server empfohlen. 


| CPU | 2 CPU-Kerne | Gleich 


| Speicher | 8 GB RAM | Gleich 


| Verfügbarer Festplattenspeicher | 50 GB (100 GB empfohlen)
Bei Linux sollte der Speicherplatz folgendermaßen zugewiesen werden:
/Opt/netapp 10 GB (20 GB für große Umgebungen)
/Var/log/netapp 40 GB (80 GB für große Umgebungen)
/Tmp mindestens 1 GB während der Installation verfügbar | 50 GB 


| Netzwerk | Ethernet-Verbindung mit 100 Mbit/s/1 Gbit/s, statische IP-Adresse und Anschluss 80 oder 443 von der Erfassungseinheit zu *.cloudinsights.netapp.com oder Ihrer Cloud Insights-Umgebung (d. h. \https://<environment_id>.c01.cloudinsights.netapp.com) sind erforderlich. Informationen zu Anforderungen zwischen Erfassungseinheit und jedem Data Collector finden Sie in der Anleitung für link:data_collector_list.html["Data Collector"].

Wenn Ihr Unternehmen Proxy-Nutzung für den Internet-Zugriff erfordert, müssen Sie möglicherweise das Proxy-Verhalten Ihrer Organisation verstehen und bestimmte Ausnahmen für Cloud Insights zu arbeiten suchen. Blockiert Ihr Unternehmen beispielsweise standardmäßig den Zugriff und gewährt ausnahmsweise nur Zugriff auf bestimmte Websites/Domänen? Wenn dies der Fall ist, müssen Sie die folgende Domäne der Ausnahmeliste hinzufügen:

*.cloudinsights.netapp.com

Weitere Informationen finden Sie unter Proxys link:task_troubleshooting_linux_acquisition_unit_problems.html#considerations-about-proxies-and-firewalls["Hier (Linux)"] Oder link:task_troubleshooting_windows_acquisition_unit_problems.html#considerations-about-proxies-and-firewalls["Hier (Windows)"]. | Gleich 


| Berechtigungen | Sudo-Berechtigungen auf dem Akquisitionsgruppenserver. /Tmp muss mit exec-Funktionen montiert werden. | Administratorberechtigungen auf dem Akquisitionsbereiches-Server 


| Virenscan |  | Während der Installation müssen Sie alle Virenscanner vollständig deaktivieren. Nach der Installation müssen die Pfade, die von der Software Acquisition Unit verwendet werden, vom Virenscan ausgeschlossen werden. 
|===


== Zusätzliche Empfehlungen

* Für eine genaue Audit- und Datenberichterstattung wird dringend empfohlen, die Zeit auf dem Acquisition Unit-Rechner mit *Network Time Protocol (NTP)* oder *Simple Network Time Protocol (SNTP)* zu synchronisieren.




== Bezüglich Der Größenanpassung

Sie können mit einer Cloud Insights Acquisition Unit mit nur 8 GB Speicher und 50 GB Festplattenspeicher beginnen. In größeren Umgebungen sollten Sie sich jedoch die folgenden Fragen stellen:

Vorteile:

* Mehr als 2500 virtuelle Maschinen oder 10 große (> 2 Nodes) ONTAP-Cluster, Symmetrix oder HDS/HPE VSP/XP-Arrays auf dieser Acquisition Unit ermitteln?
* 75 oder mehr Datensammler auf dieser Akquisitionseinheit bereitstellen?


Für jede „Ja“ Antwort oben empfiehlt es sich, 8 GB Arbeitsspeicher und 50 GB Festplattenspeicher zur AU hinzuzufügen. Wenn Sie also beispielsweise beide Fragen mit „Ja“ beantwortet haben, sollten Sie ein 24-GB-Speichersystem mit 150 GB oder mehr Festplattenspeicher implementieren. Unter Linux wird der Speicherplatz, der dem Protokollverzeichnis hinzugefügt werden soll, hinzugefügt.

Wenn Sie weitere Fragen zur Dimensionierung benötigen, wenden Sie sich an den NetApp Support.



== Zusätzliche Federal Edition-Anforderung

* Für Installationen von Akquisitionseinheiten in Cloud Insights-Clustern der Bundesausgabe muss das zugrunde liegende Betriebssystem eine gute Entropiequelle haben. Auf Linux-Systemen erfolgt dies typischerweise durch die Installation von _rng-Tools_ oder durch die Hardware-Zufallszahlengenerierung (RNG). Es liegt in der Verantwortung des Kunden, sicherzustellen, dass diese Anforderung auf der Maschine der Erfassungseinheit erfüllt wird.

