---
sidebar: sidebar 
permalink: concept_cs_api.html 
keywords: api, access, token, swagger 
summary: Workload Security umfasst eine leistungsstarke API zur Integration in andere Applikationen wie CMDBs. 
---
= Workload-Sicherheits-API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Workload-Sicherheits-API ermöglicht NetApp Kunden und unabhängigen Software-Anbietern (ISVs) die Integration der Workload-Sicherheit in andere Applikationen wie CMDB- oder andere Ticketsysteme.


NOTE: Workload-Sicherheit ist in der Cloud Insights Bundesausgabe nicht verfügbar.

Anforderungen für API-Zugriff:

* Ein API-Zugriffstoken-Modell wird verwendet, um den Zugriff zu gewähren.
* Das Management von API-Token wird von Workload Security-Benutzern mit der Administratorrolle durchgeführt.




== API-Dokumentation (Swagger)

Die neuesten API-Informationen finden Sie, indem Sie sich bei Workload Security anmelden und zu *Admin > API Access* navigieren. Klicken Sie auf den Link *API Documentation*. Die API-Dokumentation ist Swagger-basiert, die eine kurze Beschreibung und Verwendungsinformationen für die API enthält und Sie können es in Ihrer Umgebung ausprobieren.



== API-Zugriffs-Tokens

Bevor Sie die Workload Security API verwenden, müssen Sie ein oder mehrere *API Access Token* erstellen. Access Tokens gewähren Leseberechtigungen. Sie können auch die Ablauffrist für jedes Access Token festlegen.

So erstellen Sie ein Access Token:

* Klicken Sie auf *Admin > API Access*
* Klicken Sie auf *+API Access Token*
* Geben Sie *Tokenname* Ein
* Geben Sie *Token Expiration* An



NOTE: Ihr Token kann nur während des Erstellungsvorgangs in die Zwischenablage kopiert und gespeichert werden. Token können nicht abgerufen werden, nachdem sie erstellt wurden. Daher wird dringend empfohlen, das Token zu kopieren und an einem sicheren Ort zu speichern. Sie werden aufgefordert, auf die Schaltfläche API-Zugriffstoken kopieren zu klicken, bevor Sie den Bildschirm zur Token-Erstellung schließen können.

Sie können Token deaktivieren, aktivieren und widerrufen. Deaktivierte Token können aktiviert werden.

Tokens gewähren aus Kundensicht allgemeinen Zugang zu APIs und verwalten den Zugriff auf APIs im Umfang ihrer eigenen Umgebung.

Die Anwendung erhält ein Zugriffstoken, nachdem ein Benutzer den Zugriff erfolgreich authentifiziert und autorisiert hat, und übergibt das Access Token dann als Berechtigung, wenn es die Ziel-API anruft. Das übergebene Token informiert die API, dass der Inhaber des Tokens berechtigt ist, auf die API zuzugreifen und bestimmte Aktionen basierend auf dem Umfang auszuführen, den während der Autorisierung gewährt wurde.

Der HTTP-Header, in dem das Access Token übergeben wird, ist *X-CloudInsights-ApiKey:*

Verwenden Sie zum Abrufen von Lagerbeständen beispielsweise Folgendes:

 curl https://<tenant_host_name>/rest/v1/cloudsecure/activities -H 'X-CloudInsights-ApiKey: <API_Access_Token>'
Wobei _<API_Access_Token>_ das Token ist, das Sie bei der Erstellung des API-Zugriffsschlüssels gespeichert haben.

Detaillierte Informationen finden Sie im Link _API Documentation_ unter *Admin > API Access*.
