---
sidebar: sidebar 
permalink: concept_cs_agent_requirements.html 
summary: Der Server oder die VM, die Sie als Agent verwenden, müssen die Mindestanforderungen erfüllen 
keywords: agent, Linux, requirements, docker, browsers, permissions, Network, Cloud Secure 
---
= Anforderungen An Security Agent Für Workloads
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Unbedingt link:task_cs_add_agent.html["Installieren Sie einen Agenten"] Um Informationen von Ihren Datensammlern zu erhalten. Bevor Sie den Agent installieren, sollten Sie sicherstellen, dass Ihre Umgebung den Anforderungen an Betriebssystem, CPU, Arbeitsspeicher und Speicherplatz entspricht.


NOTE: Storage Workload Security ist in der Cloud Insights Bundesausgabe nicht verfügbar.

[cols="36,60"]
|===
| Komponente | Linux-Anforderungen Erfüllt 


| Betriebssystem | Ein Computer, auf dem eine lizenzierte Version einer der folgenden Versionen ausgeführt wird:

Red hat Enterprise Linux 7.x, 8.x 64-Bit, SELinux
CentOS 7.x 64-Bit, SELinux
CentOS 8 Stream, SELinux
Ubuntu 20 bis 22 64-Bit
Rocky 8.x 64-Bit, Rocky 9.x 64-Bit, SELinux
SUSE Linux Enterprise Server 15 SP3, SUSE Linux Enterprise Server 15 SP4, SELinux unter SUSE 15 SP3

Auf diesem Computer sollte keine andere Software auf Anwendungsebene ausgeführt werden. Es wird ein dedizierter Server empfohlen. 


| Befehle | Für die Installation ist „entpacken“ erforderlich. Darüber hinaus ist für die Installation, das Ausführen von Skripten und die Deinstallation der Befehl 'udo su –' erforderlich. 


| CPU | 4 CPU-Kerne 


| Speicher | 16 GB RAM 


| Verfügbarer Festplattenspeicher | Der Festplattenspeicher sollte folgendermaßen zugewiesen werden:
/Opt/netapp 35 GB (mindestens)

Hinweis: Es wird empfohlen, etwas zusätzlichen Speicherplatz zuzuweisen, um die Erstellung des Dateisystems zu ermöglichen. Stellen Sie sicher, dass mindestens 35 GB freier Speicherplatz im Dateisystem vorhanden ist.


Wenn /opt ein eingebrachter Ordner aus einem NAS-Speicher ist, stellen Sie sicher, dass lokale Benutzer Zugriff auf diesen Ordner haben. Agent oder Data Collector können nicht installiert werden, wenn lokale Benutzer nicht über die Berechtigung zu diesem Ordner verfügen. Siehe link:task_cs_add_agent.html#troubleshooting-agent-errors["Fehlerbehebung"] Weitere Informationen finden Sie in diesem Abschnitt. 


| Netzwerk | 100 Mbit/s bis 1 Gbit/s Ethernet-Verbindung, statische IP-Adresse, IP-Konnektivität zu allen Geräten und ein erforderlicher Port zur Workload Security-Instanz (80 oder 443). 
|===
Hinweis: Der Workload Security Agent kann auf demselben Rechner wie ein Cloud Insights-Erfassungsgerät und/oder -Agent installiert werden. Es ist jedoch eine Best Practice, diese in separaten Maschinen zu installieren. Wenn diese auf demselben Rechner installiert sind, weisen Sie den Festplattenspeicherplatz wie unten gezeigt zu:

|===


| Verfügbarer Festplattenspeicher | 50-55 GB für Linux sollte auf diese Weise Speicherplatz zugewiesen werden: /Opt/netapp 25-30 GB /var/log/netapp 25 GB 
|===


== Zusätzliche Empfehlungen

* Es wird dringend empfohlen, die Zeit auf dem ONTAP-System und dem Agent-Rechner mit *Network Time Protocol (NTP)* oder *Simple Network Time Protocol (SNTP)* zu synchronisieren.




== Zugriffsregeln Für Das Cloud-Netzwerk

Für * US-basierte * -Sicherheitsumgebungen:

[cols="5*"]
|===
| Protokoll | Port | Quelle | Ziel | Beschreibung 


| TCP | 443 | Workload Security Agent | <site_Name>.cs01.cloudinsights.netapp.com <site_Name>.c01.cloudinsights.netapp.com <site_Name>.c02.cloudinsights.netapp.com | Zugriff auf Cloud Insights 


| TCP | 443 | Workload Security Agent | gateway.c01.cloudinsights.netapp.com agentlogin.cs01.cloudinsights.netapp.com | Zugriff auf Authentifizierungsservices 
|===
Für *Europa-basierte* Arbeitslastsicherheitsumgebungen:

[cols="5*"]
|===
| Protokoll | Port | Quelle | Ziel | Beschreibung 


| TCP | 443 | Workload Security Agent | <site_Name>.cs01-eu-1.cloudinsights.netapp.com <site_Name>.c01-eu-1.cloudinsights.netapp.com <site_Name>.c02-eu-1.cloudinsights.netapp.com | Zugriff auf Cloud Insights 


| TCP | 443 | Workload Security Agent | gateway.c01.cloudinsights.netapp.com agentlogin.cs01-eu-1.cloudinsights.netapp.com | Zugriff auf Authentifizierungsservices 
|===
Für * APAC-basierte * -Arbeitsumgebungen:

[cols="5*"]
|===
| Protokoll | Port | Quelle | Ziel | Beschreibung 


| TCP | 443 | Workload Security Agent | <site_Name>.cs01-ap-1.cloudinsights.netapp.com <site_Name>.c01-ap-1.cloudinsights.netapp.com <site_Name>.c02-ap-1.cloudinsights.netapp.com | Zugriff auf Cloud Insights 


| TCP | 443 | Workload Security Agent | gateway.c01.cloudinsights.netapp.com agentlogin.cs01-ap-1.cloudinsights.netapp.com | Zugriff auf Authentifizierungsservices 
|===


== Netzwerkregeln

Beachten Sie, dass beim Hinzufügen von _link:task_add_collector_svm.html#permissions-when-adding-via-cluster-management-ip["CSuser"]_, dieser Benutzer benötigt SSH-Zugriff auf die ONTAP Management-LIF.

[cols="5*"]
|===
| Protokoll | Port | Quelle | Ziel | Beschreibung 


| TCP | 389 (LDAP) 636 (LDAPS/Start-tls) | Workload Security Agent | LDAP-Server-URL | Mit LDAP verbinden 


| TCP | 443 | Workload Security Agent | Cluster- oder SVM-Management-IP-Adresse (abhängig von der SVM-Collector-Konfiguration) | API-Kommunikation mit ONTAP 


| TCP | 35000 - 55000 | SVM-Daten-LIF-IP-Adressen | Workload Security Agent | Kommunikation von ONTAP zum Workload Security Agent für FPolicy-Ereignisse.  Diese Ports müssen gegenüber dem Workload Security Agent geöffnet werden, damit ONTAP Ereignisse an ihn senden kann, einschließlich jeglicher Firewall auf dem Workload Security Agent selbst (falls vorhanden). 


| TCP | 7 | Workload Security Agent | SVM-Daten-LIF-IP-Adressen | Echo vom Agent zu SVM-Daten-LIFs 


| SSH | 22 | Workload Security Agent | Cluster-Management | Erforderlich für das Blockieren von CIFS/SMB-Benutzern. 
|===


== Systemgröße

Siehe link:concept_cs_event_rate_checker.html["Ereignisprüfung"] Dokumentation für Informationen zur Größenanpassung
