---
sidebar: sidebar 
permalink: index.html 
summary: Willkommen beim Dokumentationsportal für Cloud Insights. 
keywords:  
---
= Cloud Insights-Dokumentation
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:keywords: OnCommand, Insight, documentation, help
:toc-position: content


[role="lead"]
NetApp Cloud Insights ist ein Tool für das Monitoring der Cloud-Infrastruktur, mit dem Sie Ihre gesamte Infrastruktur im Blick haben. Es überwacht nicht nur alle Ressourcen, die in Public Clouds und privaten Datacentern liegen, sondern hilft auch dabei, Fehler aufzuspüren und den Ressourceneinsatz zu optimieren. Cloud Insights



== Welche Vorteile bietet Cloud Insights für mich?

Cloud Insights bietet Hybrid-Multi-Cloud-Monitoring und ermöglicht die Beobachtung von Infrastruktur und Workloads in einem kompletten Stack.

* Datensammler für heterogene Infrastrukturen und Workloads einschließlich Kubernetes
* Offener Telegraf-Kollektor und offene APIs für eine einfache Integration
* Umfassende Warn- und Benachrichtigungen
* Maschinelles Lernen für intelligente Erkenntnisse
* Optimierte Ressourcenauslastung
* Integrierte oder anpassbare Dashboards mit erweiterten Filtern zur Reduzierung von Anzeigerauschen bei der Beantwortung von Fragen
* Der Zustand Ihrer ONTAP Storage-Vorgänge erkennen 
* Schutz Ihrer wertvollsten Geschäftsdaten – Daten – vor Ransomware oder Datenvernichtung


'''


== Erste Schritte

* Wie kann ich link:task_cloud_insights_onboarding_1.html["*Start*"] Mit Cloud Insights?
* Ich bin angemeldet. Was mache ich nun?link:task_getting_started_with_cloud_insights.html["Erfassen Von Daten"]
link:concept_user_roles.html["Benutzer einrichten"]
* Genial! Nächste Schritte
link:task_defining_annotations.html["Vorbereiten Von Ressourcen: Anmerkungen"]
link:concept_querying_assets.html["Suchen der gewünschten Assets: Abfragen"]
link:concept_dashboards_overview.html["Anzeigen der gewünschten Daten: Dashboards"]
link:task_create_monitor.html["Monitoring und Alarme"]
link:task_cs_getting_started.html["Sicherheit Der Daten"]
* Das ist tolle Sache! Ich bin bereit link:concept_subscribing_to_cloud_insights.html["*Anmeldung*"].

