---
sidebar: sidebar 
permalink: task_config_telegraf_kubernetes.html 
keywords: telegraf 
summary: Datensammler für Kubernetes 
---
= Data Collector: Kubernetes
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Insights verwendet diese Datensammler, um Kubernetes Pod, Node und Container-Kennzahlen zu erfassen.



== Installation

Eine Anleitung zur Kubernetes Installation finden Sie im link:task_config_telegraf_agent_k8s.html["Kubernetes Monitoring Operator"] Seite.



== Über Kube-State-Metrics

Der Kubernetes Monitoring Operator installiert kube-State-Metriken automatisch. Es ist keine Benutzerinteraktion erforderlich.



=== Kube-State-metrics-Zähler

Der NetApp-Kubernetes-Überwachungsoperator extrahiert die unten aufgeführten Kennzahlen für den kube-Status. Weitere Details zu den einzelnen Zählerwidersetzen finden Sie unter: https://github.com/kubernetes/kube-state-metrics/tree/main/docs#exposed-metrics[].

. Kennzahlen für die Konfigmap
. DemonSet Metrics
. Implementierungsmetriken
. Ingress Metrics
. Namespace-Kennzahlen
. Node-Kennzahlen
. Persistente Volume-Kennzahlen
. Persistent Volume Claim Metrics
. Pod-Metriken
. Kennzahlen für ReplicaSet
. Geheimkennzahlen
. Service-Kennzahlen
. StatfulSet-Kennzahlen

