---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: ECS-Datensammler konfigurieren. 
---
= Konfigurieren des EMC ECS-Datensammlers
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Dieser Datensammler erfasst Bestands- und Performancedaten von EMC ECS Speichersystemen. Zur Konfiguration benötigt der Datensammler eine IP-Adresse des ECS-Servers und ein Domain-Konto auf Administratorebene.


NOTE: Dell EMC ECS wird mit einer anderen Rate von Raw TB zu Managed Units gemessen. Alle 40 TB unformatierte ECS-Kapazität wird als 1 geladen link:concept_subscribing_to_cloud_insights.html#pricing["Verwaltete Einheit (ME)"].



== Terminologie

Cloud Insights erwirbt die folgenden Bestandsinformationen vom ECS Datensammler. Für jeden erfassten Asset-Typ wird die am häufigsten für dieses Dokument verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Laufzeit Für Cloud Insights 


| Cluster | Storage 


| Mandant | Storage-Pool 


| Eimer | Internes Volumen 


| Festplatte | Festplatte 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

* Eine IP-Adresse der ECS Management Console
* Domain-Konto auf Administratorebene für das ECS-System
* Port 443 (HTTPS): Erfordert eine ausgehende Verbindung zum TCP-Port 443 des ECS-Systems.
* Für die Leistung können Sie den schreibgeschützten Benutzernamen und das Kennwort für den ssh/scp-Zugriff verwenden.
* Für die Leistung ist Port 22 erforderlich.




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| ECS Host | IP-Adresse oder vollqualifizierter Domain-Name des ECS-Systems 


| ECS-Host-Port | Port, der für die Kommunikation mit ECS Host verwendet wird 


| ECS Anbieter-ID | Anbieter-ID für ECS 


| Passwort | Passwort wird für ECS verwendet 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Abfrageintervall für Bestand (min) | Der Standardwert ist 360 Minuten. 
|===


== Fehlerbehebung

Weitere Informationen finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:reference_data_collector_support_matrix.html["Data Collector Supportmatrix"].
