---
sidebar: sidebar 
permalink: task_dc_ms_hyperv.html 
keywords: data collector, Microsoft, Hyper-V 
summary: Microsoft Hyper-V-Datensammler konfigurieren. 
---
= Microsoft Hyper-V Datensammler
:allow-uri-read: 


[role="lead"]
7715b27c3c633c894edbc1c3480d311c



== Terminologie

Cloud Insights erwirbt die folgenden Bestandsinformationen vom Microsoft Hyper-V (WMI). Die am häufigsten für diese Ressource verwendete Terminologie wird für jeden von Cloud Insights erfassten Asset-Typ angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Laufzeit Für Cloud Insights 


| Virtuelle Festplatte | Virtuelles Laufwerk 


| Host | Host 


| Virtual Machine | Virtual Machine 


| Cluster Shared Volumes (CSV), Partition Volume | Datastore 


| Internet SCSI-Gerät, Multi Path SCSI LUN | LUN 


| Fibre Channel-Port | Port 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

Zur Konfiguration dieses Datensammlers sind folgende Voraussetzungen erforderlich:

* Für die Hyper-V muss Port 5985 geöffnet sein, damit Daten erfasst und Remote-Zugriff/-Management erfolgen können.
* ecda38bc28a47936b29d11e115c3da48
* 0d2113f67a7658f557c02b2de3f05cf1
* 6c3c9df6e16d0246aaa0ec5441c04561
* 8c1948e0309134002250ecab98bf55ec
* Port-Anforderungen: Port 135 über WMI & Dynamic TCP Ports zugewiesen 1024-65535 für Windows 2003 und älter und 49152-65535 für Windows 2008.
* DNS-Auflösung muss erfolgreich sein, auch wenn der Datensammler nur auf eine IP-Adresse verweist
* cdc59ca9a737e48e94e58966b33d355f
+
link:https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831661(v=ws.11)["Hyper-V Übersicht zur Ressourcenmessung"]

+
link:https://docs.microsoft.com/en-us/powershell/module/hyper-v/enable-vmresourcemetering?view=win10-ps["Aktivieren-VMressourcenMetering"]




NOTE: Für den Hyper-V-Datensammler ist eine Windows Acquisition Unit erforderlich.



== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| 48b865172aa7a91dee1b9137be290087 | 93a540a173a30e909c6fc0df2f5f12cd 


| Benutzername | Administrator-Benutzername für den Hypervisor 


| Passwort | Kennwort für den Hypervisor 


| 7eaf62c20e3754bb13a378f4a1535681 | 3f47a0b347b090238ebf3146d05878eb 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Abfrageintervall für Bestand (min) | Der Standardwert ist 20 Minuten. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Data Collector finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
